import type { User, Project, Task, NotifItem } from './types';

export const USERS: User[] = [
  { id: 'u1',  name: 'Rajan Kapoor',  role: 'director', avatar: 'RK', userStatus: 'active',  email: 'rajan@garagecollective.io',   tasksCompleted: 0  },
  { id: 'u2',  name: 'Priya Shah',    role: 'teamLead', department: 'Developer',            avatar: 'PS', userStatus: 'active',  email: 'priya@garagecollective.io',   tasksCompleted: 12 },
  { id: 'u3',  name: 'Pooja Nair',    role: 'teamLead', department: 'Design',               avatar: 'PN', userStatus: 'away',    email: 'pooja@garagecollective.io',   tasksCompleted: 9  },
  { id: 'u4',  name: 'Kavita Joshi',  role: 'teamLead', department: 'Social Media',         avatar: 'KJ', userStatus: 'active',  email: 'kavita@garagecollective.io',  tasksCompleted: 15 },
  { id: 'u5',  name: 'Arjun Patel',   role: 'teamLead', department: 'Business Development', avatar: 'AP', userStatus: 'active',  email: 'arjun@garagecollective.io',   tasksCompleted: 7  },
  { id: 'u6',  name: 'Shreya Iyer',   role: 'teamLead', department: 'SEO',                  avatar: 'SI', userStatus: 'away',    email: 'shreya@garagecollective.io',  tasksCompleted: 11 },
  { id: 'u7',  name: 'Rohit Verma',   role: 'member',   department: 'Developer',            avatar: 'RV', userStatus: 'active',  email: 'rohit@garagecollective.io',   tasksCompleted: 6  },
  { id: 'u8',  name: 'Anjali Desai',  role: 'member',   department: 'Design',               avatar: 'AD', userStatus: 'offline', email: 'anjali@garagecollective.io',  tasksCompleted: 4  },
  { id: 'u9',  name: 'Suresh Kumar',  role: 'member',   department: 'Social Media',         avatar: 'SK', userStatus: 'active',  email: 'suresh@garagecollective.io',  tasksCompleted: 8  },
  { id: 'u10', name: 'Neha Gupta',    role: 'member',   department: 'Developer',            avatar: 'NG', userStatus: 'away',    email: 'neha@garagecollective.io',    tasksCompleted: 5  },
  { id: 'u11', name: 'Vivek Sharma',  role: 'member',   department: 'Business Development', avatar: 'VS', userStatus: 'active',  email: 'vivek@garagecollective.io',   tasksCompleted: 3  },
  { id: 'u12', name: 'Divya Reddy',   role: 'member',   department: 'SEO',                  avatar: 'DR', userStatus: 'active',  email: 'divya@garagecollective.io',   tasksCompleted: 7  },
];

export const SEED_PROJECTS: Project[] = [
  { id:'p1',  name:'E-commerce Website',          department:'Developer',            owner:'Priya Shah',   ownerId:'u2', status:'inProgress', progress:65,  dueDate:'2026-03-20', createdDate:'2026-01-10', team:['PS','RV','NG'], issues:{todo:5,active:5,done:12},  priority:'high',     description:'Full-stack e-commerce platform for RetailPro client.',        client:'RetailPro'   },
  { id:'p2',  name:'Brand Redesign',              department:'Design',               owner:'Pooja Nair',   ownerId:'u3', status:'inProgress', progress:45,  dueDate:'2026-03-15', createdDate:'2026-01-20', team:['PN','AD'],      issues:{todo:8,active:3,done:7},   priority:'critical', description:'Complete visual identity overhaul for TechWave.',             client:'TechWave'    },
  { id:'p3',  name:'Instagram Campaign Q1',       department:'Social Media',         owner:'Kavita Joshi', ownerId:'u4', status:'inProgress', progress:80,  dueDate:'2026-03-10', createdDate:'2026-01-05', team:['KJ','SK'],      issues:{todo:2,active:4,done:15},  priority:'high',     description:'Q1 social media campaign across Instagram & TikTok.',        client:'StyleZone'   },
  { id:'p4',  name:'AI Chatbot Integration',      department:'Developer',            owner:'Priya Shah',   ownerId:'u2', status:'backlog',    progress:15,  dueDate:'2026-04-01', createdDate:'2026-02-01', team:['PS','RV'],      issues:{todo:12,active:1,done:2},  priority:'medium',   description:'AI-powered support chatbot using GPT-4 API.',                client:'FinServe'    },
  { id:'p5',  name:'Mobile App UI Design',        department:'Design',               owner:'Pooja Nair',   ownerId:'u3', status:'done',       progress:100, dueDate:'2026-03-01', createdDate:'2025-12-01', team:['PN','AD'],      issues:{todo:0,active:0,done:18},  priority:'low',      description:'iOS & Android UI design for FitTrack app.',                  client:'FitTrack'    },
  { id:'p6',  name:'Email Marketing Automation',  department:'Social Media',         owner:'Kavita Joshi', ownerId:'u4', status:'backlog',    progress:10,  dueDate:'2026-03-25', createdDate:'2026-02-10', team:['KJ','SK'],      issues:{todo:9,active:1,done:1},   priority:'medium',   description:'Automated drip campaigns for lead nurturing.',                client:'GrowthHub'   },
  { id:'p7',  name:'Investor Pitch Deck',         department:'Business Development', owner:'Arjun Patel',  ownerId:'u5', status:'inProgress', progress:55,  dueDate:'2026-03-18', createdDate:'2026-02-05', team:['AP','VS'],      issues:{todo:4,active:3,done:5},   priority:'critical', description:'Series A funding pitch deck for internal startup.',           client:'Internal'    },
  { id:'p8',  name:'Partnership Proposal - MENA', department:'Business Development', owner:'Arjun Patel',  ownerId:'u5', status:'backlog',    progress:20,  dueDate:'2026-04-10', createdDate:'2026-02-15', team:['AP','VS'],      issues:{todo:6,active:2,done:1},   priority:'high',     description:'Regional partnership proposal targeting MENA market.',        client:'NovaCorp'    },
  { id:'p9',  name:'SEO Audit & Strategy',        department:'SEO',                  owner:'Shreya Iyer',  ownerId:'u6', status:'inProgress', progress:70,  dueDate:'2026-03-12', createdDate:'2026-01-25', team:['SI','DR'],      issues:{todo:3,active:5,done:10},  priority:'high',     description:'Technical SEO audit and 6-month content strategy.',          client:'MediCare'    },
  { id:'p10', name:'Blog Content Calendar',       department:'SEO',                  owner:'Shreya Iyer',  ownerId:'u6', status:'inProgress', progress:40,  dueDate:'2026-03-30', createdDate:'2026-02-08', team:['SI','DR'],      issues:{todo:7,active:3,done:4},   priority:'medium',   description:'Q2 editorial calendar with 50+ SEO-optimized articles.',     client:'EduLearn'    },
  { id:'p11', name:'Website Revamp',              department:'Developer',            owner:'Priya Shah',   ownerId:'u2', status:'backlog',    progress:5,   dueDate:'2026-04-15', createdDate:'2026-02-20', team:['PS','NG'],      issues:{todo:15,active:0,done:1},  priority:'medium',   description:'Full rebuild of client website on Next.js 15.',              client:'LuxHomes'    },
  { id:'p12', name:'TikTok Ad Strategy',          department:'Social Media',         owner:'Kavita Joshi', ownerId:'u4', status:'done',       progress:100, dueDate:'2026-02-28', createdDate:'2025-12-15', team:['KJ','SK'],      issues:{todo:0,active:0,done:12},  priority:'low',      description:'TikTok paid ads and organic growth strategy.',               client:'SnapStyle'   },
];

export const SEED_TASKS: Task[] = [
  { id:'t1',  title:'Fix authentication bug',       projectId:'p1',  project:'E-commerce Website',          department:'Developer',            priority:'critical', status:'inProgress', assigneeId:'u7',  assignee:'Rohit Verma',   dueDate:'2026-03-07', description:'JWT token refresh failing on mobile browsers.',          createdById:'u2', createdBy:'Priya Shah'  },
  { id:'t2',  title:'Design homepage mockup',       projectId:'p2',  project:'Brand Redesign',              department:'Design',               priority:'high',     status:'inProgress', assigneeId:'u8',  assignee:'Anjali Desai',  dueDate:'2026-03-08', description:'3 homepage layout variations for client review.',        createdById:'u3', createdBy:'Pooja Nair'  },
  { id:'t3',  title:'Create Instagram posts (10)',  projectId:'p3',  project:'Instagram Campaign Q1',       department:'Social Media',         priority:'high',     status:'backlog',    assigneeId:'u9',  assignee:'Suresh Kumar',  dueDate:'2026-03-09', description:'10 branded posts for March campaign batch.',            createdById:'u4', createdBy:'Kavita Joshi'},
  { id:'t4',  title:'Setup database schema',        projectId:'p4',  project:'AI Chatbot Integration',      department:'Developer',            priority:'medium',   status:'backlog',    assigneeId:'u7',  assignee:'Rohit Verma',   dueDate:'2026-03-12', description:'MongoDB schema for conversation history & context.',     createdById:'u2', createdBy:'Priya Shah'  },
  { id:'t5',  title:'User testing feedback review', projectId:'p5',  project:'Mobile App UI Design',        department:'Design',               priority:'low',      status:'done',       assigneeId:'u8',  assignee:'Anjali Desai',  dueDate:'2026-02-28', description:'Collate and prioritize user feedback from beta.',        createdById:'u3', createdBy:'Pooja Nair'  },
  { id:'t6',  title:'Configure email templates',    projectId:'p6',  project:'Email Marketing Automation',  department:'Social Media',         priority:'medium',   status:'backlog',    assigneeId:'u9',  assignee:'Suresh Kumar',  dueDate:'2026-03-15', description:'HTML templates for welcome, nurture, and win-back.',     createdById:'u4', createdBy:'Kavita Joshi'},
  { id:'t7',  title:'Payment gateway integration',  projectId:'p1',  project:'E-commerce Website',          department:'Developer',            priority:'high',     status:'backlog',    assigneeId:'u10', assignee:'Neha Gupta',    dueDate:'2026-03-10', description:'Stripe + PayTabs dual integration.',                    createdById:'u2', createdBy:'Priya Shah'  },
  { id:'t8',  title:'Logo variations (5)',          projectId:'p2',  project:'Brand Redesign',              department:'Design',               priority:'critical', status:'inProgress', assigneeId:'u3',  assignee:'Pooja Nair',    dueDate:'2026-03-07', description:'5 logo concepts with dark/light/monochrome variants.',  createdById:'u3', createdBy:'Pooja Nair'  },
  { id:'t9',  title:'API rate limit handling',      projectId:'p1',  project:'E-commerce Website',          department:'Developer',            priority:'medium',   status:'backlog',    assigneeId:'u10', assignee:'Neha Gupta',    dueDate:'2026-03-14', description:'Graceful degradation when 3rd-party APIs throttle.',    createdById:'u2', createdBy:'Priya Shah'  },
  { id:'t10', title:'Prepare slide deck outline',   projectId:'p7',  project:'Investor Pitch Deck',         department:'Business Development', priority:'critical', status:'inProgress', assigneeId:'u11', assignee:'Vivek Sharma',  dueDate:'2026-03-08', description:'10-slide structure with financial projections.',         createdById:'u5', createdBy:'Arjun Patel' },
  { id:'t11', title:'Competitive analysis report',  projectId:'p8',  project:'Partnership Proposal - MENA', department:'Business Development', priority:'high',     status:'backlog',    assigneeId:'u11', assignee:'Vivek Sharma',  dueDate:'2026-03-16', description:'MENA digital agency landscape analysis.',               createdById:'u5', createdBy:'Arjun Patel' },
  { id:'t12', title:'Technical SEO audit',          projectId:'p9',  project:'SEO Audit & Strategy',        department:'SEO',                  priority:'high',     status:'inProgress', assigneeId:'u12', assignee:'Divya Reddy',   dueDate:'2026-03-11', description:'Core Web Vitals, crawl errors, structured data review.', createdById:'u6', createdBy:'Shreya Iyer' },
  { id:'t13', title:'Keyword research - Blog Q2',   projectId:'p10', project:'Blog Content Calendar',        department:'SEO',                  priority:'medium',   status:'backlog',    assigneeId:'u12', assignee:'Divya Reddy',   dueDate:'2026-03-20', description:'300 target keywords mapped to content topics.',          createdById:'u6', createdBy:'Shreya Iyer' },
  { id:'t14', title:'Product page component build', projectId:'p1',  project:'E-commerce Website',          department:'Developer',            priority:'high',     status:'inProgress', assigneeId:'u7',  assignee:'Rohit Verma',   dueDate:'2026-03-13', description:'Reusable product card, gallery, and reviews section.',  createdById:'u2', createdBy:'Priya Shah'  },
  { id:'t15', title:'Icon set design',              projectId:'p2',  project:'Brand Redesign',              department:'Design',               priority:'medium',   status:'backlog',    assigneeId:'u8',  assignee:'Anjali Desai',  dueDate:'2026-03-18', description:'24 custom icons for brand style guide.',                createdById:'u3', createdBy:'Pooja Nair'  },
  { id:'t16', title:'Stories & Reels content',      projectId:'p3',  project:'Instagram Campaign Q1',       department:'Social Media',         priority:'medium',   status:'inProgress', assigneeId:'u9',  assignee:'Suresh Kumar',  dueDate:'2026-03-10', description:'8 reels + 15 story slides for week 2 drop.',            createdById:'u4', createdBy:'Kavita Joshi'},
  { id:'t17', title:'Backlink outreach list',        projectId:'p9',  project:'SEO Audit & Strategy',        department:'SEO',                  priority:'medium',   status:'done',       assigneeId:'u12', assignee:'Divya Reddy',   dueDate:'2026-03-05', description:'100 high-DA prospects for guest post outreach.',         createdById:'u6', createdBy:'Shreya Iyer' },
  { id:'t18', title:'Deploy staging environment',   projectId:'p4',  project:'AI Chatbot Integration',      department:'Developer',            priority:'medium',   status:'backlog',    assigneeId:'u10', assignee:'Neha Gupta',    dueDate:'2026-03-22', description:'Docker + Vercel staging pipeline setup.',               createdById:'u2', createdBy:'Priya Shah'  },
];

export const SEED_NOTIFS: NotifItem[] = [
  { id:'n1', triggerUser:'Rajan Kapoor', action:'created project',                  targetName:'AI Chatbot Integration', timestamp: Date.now()-5*60000,    unread:true,  type:'project_created', forRoles:['director','teamLead'] },
  { id:'n2', triggerUser:'Priya Shah',   action:'updated status to In Progress for', targetName:'E-commerce Website',     timestamp: Date.now()-15*60000,   unread:true,  type:'status_updated',  forRoles:['director','teamLead'] },
  { id:'n3', triggerUser:'Pooja Nair',   action:'completed task in',                 targetName:'Brand Redesign',          timestamp: Date.now()-60*60000,   unread:false, type:'task_completed',  forRoles:['director','teamLead'] },
  { id:'n4', triggerUser:'Kavita Joshi', action:'assigned you a task in',            targetName:'Instagram Campaign Q1',   timestamp: Date.now()-2*3600000,  unread:true,  type:'task_assigned',   forRoles:['member'], forUserId:'u9' },
  { id:'n5', triggerUser:'Priya Shah',   action:'assigned you a task in',            targetName:'E-commerce Website',      timestamp: Date.now()-3*3600000,  unread:true,  type:'task_assigned',   forRoles:['member'], forUserId:'u7' },
];
